#User defined
user:
  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - latest
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION

  # install_PHPERROR:
  #   label:
  #     Install PHPERROR?
  #   type:
  #     select
  #   values:
  #     - On
  #     - Off
  #   hint:
  #     Check to On/Off display error
  #   target:
  #     DISPLAY_PHPERROR
  # mysql_version:
  #   label:
  #     MySQL version
  #   hint:
  #     Select MySQL version
  #   type:
  #     select
  #   values:
  #     - "5.0"
  #     - "7.0"
  #   target:
  #     MYSQL_VERSION

  # customize_server_root_path:
  #   label:
  #     Server root
  #   type:
  #     input
  #   values:
  #     /var/www
  #   hint:
  #     Server document root
  #   target:
  #     SERVER_ROOT

#System defaults
system:
  # show_localpath_selector:
  #   true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      PMA_PORT
    others:
      - MYSQL_PORT


