name: MariaDB

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Mariadb 10.5
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MARIADB_VERSION: "10.5"
    - name: Verify MariaDB running from host, create Database and show Database
      run: |
        sleep 30s
    - name: Check MariaDB version
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
    - name: Verify MariaDB database from user
      run:  docker exec mariadb_mariadb_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
    - name: Verify Database create or not
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: Docker Image Down and data deleted
      run:  |
        docker-compose -f "docker-compose.yml" down
        sudo rm -rf /tmp/mysql

    
    - name: Build the Docker image Mariadb 10.6
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MARIADB_VERSION: "10.6"
    - name: Verify MariaDB running from host, create Database and show Database
      run: |
        sleep 30s
    - name: Check MariaDB version
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
    - name: Verify MariaDB database from user
      run:  docker exec mariadb_mariadb_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
    - name: Verify Database create or not
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: Docker Image Down and data deleted
      run:  |
        docker-compose -f "docker-compose.yml" down
        sudo rm -rf /tmp/mysql


    - name: Build the Docker image Mariadb 10.7
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MARIADB_VERSION: "10.7"
    - name: Verify MariaDB running from host, create Database and show Database
      run: |
        sleep 30s
    - name: Check MariaDB version
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
    - name: Verify MariaDB database from user
      run:  docker exec mariadb_mariadb_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
    - name: Verify Database create or not
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: Docker Image Down and data deleted
      run:  |
        docker-compose -f "docker-compose.yml" down
        sudo rm -rf /tmp/mysql


    - name: Build the Docker image Mariadb latest
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MARIADB_VERSION: "latest"
    - name: Verify MariaDB running from host, create Database and show Database
      run: |
        sleep 30s
    - name: Check MariaDB version
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
    - name: Verify MariaDB database from user
      run:  docker exec mariadb_mariadb_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
    - name: Verify Database create or not
      run:  docker exec mariadb_mariadb_1 mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: Docker Image Down and data deleted
      run:  |
        docker-compose -f "docker-compose.yml" down
        sudo rm -rf /tmp/mysql